-- ===== supabase-setup.sql =====
-- این اسکریپت را یک‌بار در SQL Editor پروژه Supabase خود اجرا کنید.

-- ۱) ساخت جدول نامه‌ها
create table if not exists public.letters (
  id bigint generated by default as identity primary key,
  number text not null,
  date text not null,
  title text not null,
  recipient text not null,
  reg text not null,
  created_at timestamptz not null default now()
);

-- ۲) فعال‌سازی Row Level Security (الزامی در Supabase)
alter table public.letters enable row level security;

-- ۳) اجازه به همه (کلید anon) برای خواندن/نوشتن
--    توجه: چون سایت بدون سیستم لاگین است، این سیاست باز است —
--    یعنی هرکسی که آدرس سایت و کلید anon را داشته باشد می‌تواند نامه اضافه/ویرایش/حذف کند.
--    برای یک ابزار داخلی/تیمی معمولاً کافی است، اما اگر لازم شد بعداً می‌توان
--    با افزودن سیستم ورود کاربر (Supabase Auth) این سیاست‌ها را محدودتر کرد.
create policy "Public read access"
  on public.letters for select
  using (true);

create policy "Public insert access"
  on public.letters for insert
  with check (true);

create policy "Public update access"
  on public.letters for update
  using (true);

create policy "Public delete access"
  on public.letters for delete
  using (true);

-- ۴) فعال‌سازی realtime برای این جدول (برای به‌روزرسانی زنده بین کاربران)
alter publication supabase_realtime add table public.letters;

-- ۵) (اختیاری) چند ردیف نمونه — اگر نمی‌خواهید داده نمونه داشته باشید این بخش را حذف کنید
insert into public.letters (number, date, title, recipient, reg) values
  ('1403/120', '1403/03/12', 'ابلاغ بخشنامه اداری', 'واحد منابع انسانی', '1001'),
  ('1403/121', '1403/03/14', 'درخواست خرید تجهیزات', 'مدیریت تدارکات', '1002'),
  ('1403/122', '1403/03/15', 'گزارش عملکرد ماهانه', 'هیئت مدیره', '1003');


-- ===================================================================
-- بخش ورود (Login) — بدون استفاده از سرویس Supabase Auth
-- فقط از دیتابیس استفاده می‌شود تا اعتبار/سهمیه‌ی سرویس Auth مصرف نشود.
-- نام کاربری/رمز عبور داخل جدولی در همین دیتابیس ذخیره و به‌صورت هش‌شده
-- (bcrypt) نگهداری می‌شوند. بررسی رمز عبور فقط از طریق یک تابع (RPC)
-- انجام می‌شود و جدول به‌هیچ‌وجه از بیرون (anon) قابل خواندن نیست —
-- یعنی حتی هش رمز عبور هم برای کلاینت قابل مشاهده نخواهد بود.
-- ===================================================================

-- ۶) فعال‌سازی افزونه‌ی رمزنگاری (برای هش کردن رمز عبور)
create extension if not exists pgcrypto;

-- ۷) جدول کاربران ادمین
create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now()
);

-- فعال‌سازی RLS — و توجه کنید هیچ policy ای برای آن تعریف نمی‌شود،
-- یعنی نه anon و نه هیچ نقش دیگری اجازه‌ی select/insert/update/delete مستقیم ندارد.
alter table public.admin_users enable row level security;

-- ۸) ثبت کاربر پیش‌فرض (نام کاربری: mstadmin — رمز عبور: mst123456)
insert into public.admin_users (username, password_hash)
values ('mstadmin', crypt('mst123456', gen_salt('bf')))
on conflict (username) do nothing;

-- ۹) تابع بررسی ورود — تنها راه مجاز برای چک کردن نام کاربری/رمز عبور.
--    security definer یعنی این تابع با اختیارات مالک اجرا می‌شود، پس با
--    وجود RLS باز هم می‌تواند جدول admin_users را بخواند، ولی خروجی آن
--    فقط true/false است و هیچ داده‌ی خامی به بیرون درز نمی‌کند.
create or replace function public.verify_admin_login(p_username text, p_password text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  stored_hash text;
begin
  select password_hash into stored_hash
  from public.admin_users
  where username = p_username;

  if stored_hash is null then
    return false;
  end if;

  return stored_hash = crypt(p_password, stored_hash);
end;
$$;

-- ۱۰) فقط اجازه‌ی «اجرا» به این تابع داده می‌شود، نه دسترسی به جدول
revoke all on function public.verify_admin_login(text, text) from public;
grant execute on function public.verify_admin_login(text, text) to anon, authenticated;
