-- ===== supabase-setup.sql =====
-- این اسکریپت را یک‌بار در SQL Editor پروژه Supabase خود اجرا کنید.

-- ۱) ساخت جدول نامه‌ها
create table if not exists public.letters (
  id bigint generated by default as identity primary key,
  number text not null,
  date text not null,
  title text not null,
  recipient text not null,
  reg text not null,
  created_at timestamptz not null default now()
);

-- ۲) فعال‌سازی Row Level Security (الزامی در Supabase)
alter table public.letters enable row level security;

-- ۳) اجازه به همه (کلید anon) برای خواندن/نوشتن
--    توجه: چون سایت بدون سیستم لاگین است، این سیاست باز است —
--    یعنی هرکسی که آدرس سایت و کلید anon را داشته باشد می‌تواند نامه اضافه/ویرایش/حذف کند.
--    برای یک ابزار داخلی/تیمی معمولاً کافی است، اما اگر لازم شد بعداً می‌توان
--    با افزودن سیستم ورود کاربر (Supabase Auth) این سیاست‌ها را محدودتر کرد.
create policy "Public read access"
  on public.letters for select
  using (true);

create policy "Public insert access"
  on public.letters for insert
  with check (true);

create policy "Public update access"
  on public.letters for update
  using (true);

create policy "Public delete access"
  on public.letters for delete
  using (true);

-- ۴) فعال‌سازی realtime برای این جدول (برای به‌روزرسانی زنده بین کاربران)
alter publication supabase_realtime add table public.letters;

-- ۵) (اختیاری) چند ردیف نمونه — اگر نمی‌خواهید داده نمونه داشته باشید این بخش را حذف کنید
insert into public.letters (number, date, title, recipient, reg) values
  ('1403/120', '1403/03/12', 'ابلاغ بخشنامه اداری', 'واحد منابع انسانی', '1001'),
  ('1403/121', '1403/03/14', 'درخواست خرید تجهیزات', 'مدیریت تدارکات', '1002'),
  ('1403/122', '1403/03/15', 'گزارش عملکرد ماهانه', 'هیئت مدیره', '1003');
